[package]
name = "mtg_database"
version = "0.1.0"
edition = "2021"
authors = ["Ziyan"]

[dependencies]
csv = "1.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
serde_path_to_error = "0.1.17"
rusqlite = "0.31.0"
postgres = "0.19.10"
dotenvy = "0.15.7"
